// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CatalogoWebMVC.Data
{
    public partial class CATALOGO_WEB_DBContext : IdentityDbContext
    {
        public CATALOGO_WEB_DBContext()
        {
        }

        public CATALOGO_WEB_DBContext(DbContextOptions<CATALOGO_WEB_DBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Articulo> Articulos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Favorito> Favoritos { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        //public virtual DbSet<User> Users { get; set; }

       

       
    }
}