// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CatalogoWebMVC.Data
{
    [Table("MARCAS")]
    public partial class Marca
    {
        [Key]
        [Display(Name ="Marca")]
        public int Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Descripcion { get; set; }
    }
}