// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CatalogoWebMVC.Data
{
    [Keyless]
    [Table("USERS")]
    public partial class User
    {
        public int Id { get; set; }
        [Required]
        [Column("email")]
        [StringLength(100)]
        [Unicode(false)]
        public string Email { get; set; }
        [Required]
        [Column("pass")]
        [StringLength(20)]
        [Unicode(false)]
        public string Pass { get; set; }
        [Column("nombre")]
        [StringLength(50)]
        [Unicode(false)]
        public string Nombre { get; set; }
        [Column("apellido")]
        [StringLength(50)]
        [Unicode(false)]
        public string Apellido { get; set; }
        [Column("urlImagenPerfil")]
        [StringLength(500)]
        [Unicode(false)]
        public string UrlImagenPerfil { get; set; }
        [Column("admin")]
        public bool Admin { get; set; }
    }
}